//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmetProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sliders
    {
        public int slider_id { get; set; }
        public string slider_img { get; set; }
        public Nullable<double> slider_price { get; set; }
        public string slider_title { get; set; }
        public string slider_description { get; set; }
    }
}
