//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmetProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int id { get; set; }
        public string facebook_url { get; set; }
        public string instagram_url { get; set; }
        public string twitter_url { get; set; }
        public string linkedin_url { get; set; }
        public string discord_url { get; set; }
    }
}
