//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmetProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAdress
    {
        public int useradress_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string useradress_province { get; set; }
        public string useradress_town { get; set; }
        public string useradress_explicitadress { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
